### ISSUE TITLE
ошибка установки libgdal2

### ISSUE THREAD

**Issue by simgislab** [nextgis/ppa#1]
> sim@sim-think:~$ sudo apt-get install libgdal2
> [sudo] password for sim: 
> Чтение списков пакетов… Готово
> Построение дерева зависимостей  
> Чтение информации о состоянии… Готово
> Следующие пакеты устанавливались автоматически и больше не требуются:
>   libgeos-3.4.2 libqgis-analysis2.14.0 libqgis-app2.14.0 libqgis-core2.14.0
>   libqgis-gui2.14.0 libqgis-networkanalysis2.14.0 libqgis-server2.14.0
>   libqgisgrass6-2.14.0 libqgispython2.14.0
> Для их удаления используйте «apt-get autoremove».
> Будут установлены следующие дополнительные пакеты:
>   libgeos-3.5.0 libgeos-c1 libgeos-c1v5 libgeos-dev
> Предлагаемые пакеты:
>   libgeos-doc
> НОВЫЕ пакеты, которые будут установлены:
>   libgdal2 libgeos-3.5.0 libgeos-c1v5
> Пакеты, которые будут обновлены:
>   libgeos-c1 libgeos-dev
> обновлено 2, установлено 3 новых пакетов, для удаления отмечено 0 пакетов, и 3 пакетов не обновлено.
> Необходимо скачать 4 465 kБ архивов.
> После данной операции, объём занятого дискового пространства возрастёт на 15,7 MB.
> Хотите продолжить? [Д/н] y
> Получено:1 http://ppa.launchpad.net/nextgis/ppa/ubuntu/ trusty/main libgeos-dev i386 3.5.0+5-0trusty1 [151 kB]
> Получено:2 http://ppa.launchpad.net/nextgis/ppa/ubuntu/ trusty/main libgeos-3.5.0 i386 3.5.0+5-0trusty1 [559 kB]
> Получено:3 http://ppa.launchpad.net/nextgis/ppa/ubuntu/ trusty/main libgeos-c1 i386 3.5.0+2-0trusty1 [189 kB]
> Получено:4 http://ppa.launchpad.net/nextgis/ppa/ubuntu/ trusty/main libgeos-c1v5 i386 3.5.0+5-0trusty1 [190 kB]
> Получено:5 http://ppa.launchpad.net/nextgis/ppa/ubuntu/ trusty/main libgdal2 i386 2.1.0+37-0trusty1 [3 377 kB]
> Получено 4 465 kБ за 6с (650 kБ/c)  
> (Чтение базы данных … на данный момент установлено 410889 файлов и каталогов.)
> Preparing to unpack …/libgeos-dev_3.5.0+5-0trusty1_i386.deb ...
> Unpacking libgeos-dev (3.5.0+5-0trusty1) over (3.4.2-4ubuntu1) ...
> Выбор ранее не выбранного пакета libgeos-3.5.0.
> Preparing to unpack …/libgeos-3.5.0_3.5.0+5-0trusty1_i386.deb ...
> Unpacking libgeos-3.5.0 (3.5.0+5-0trusty1) ...
> Preparing to unpack …/libgeos-c1_3.5.0+2-0trusty1_i386.deb ...
> Unpacking libgeos-c1 (3.5.0+2-0trusty1) over (3.4.2-4ubuntu1) ...
> Выбор ранее не выбранного пакета libgeos-c1v5.
> Preparing to unpack …/libgeos-c1v5_3.5.0+5-0trusty1_i386.deb ...
> Unpacking libgeos-c1v5 (3.5.0+5-0trusty1) ...
> dpkg: error processing archive /var/cache/apt/archives/libgeos-c1v5_3.5.0+5-0trusty1_i386.deb (--unpack):
>  попытка перезаписать «/usr/lib/i386-linux-gnu/libgeos_c.so.1.9.0», который уже имеется в пакете libgeos-c1 3.5.0+2-0trusty1
> dpkg-deb: ошибка: подпроцесс вставка уничтожен по сигналу (Обрыв канала)
> Выбор ранее не выбранного пакета libgdal2.
> Preparing to unpack …/libgdal2_2.1.0+37-0trusty1_i386.deb ...
> Unpacking libgdal2 (2.1.0+37-0trusty1) ...
> Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
> При обработке следующих пакетов произошли ошибки:
>  /var/cache/apt/archives/libgeos-c1v5_3.5.0+5-0trusty1_i386.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by BishopGIS** [comment]
Проблема в конфликте наименований пакетов. Т.е. на уровне софта вроде нет проблем.
Что бы разрешить конфликт мне надо узнать из какого репозитория ставится QGIS 2.14.
В официально репе только 2.8.6
http://packages.ubuntu.com/search?keywords=qgis

В Ubuntugis-stable - 2.2.0
В Ubuntugis-unstable - 2.8.1

Кажется вот от сюда: http://qgis.org/debian (http://qgis.org/debian/dists/trusty/main/binary-i386/Packages)

Вот список зависимостей:
- libc6 (>= 2.4)
- libgcc1 (>= 1:4.1.1)
- libgdal1h (>= 1.8.0)
- libgeos-c1 (>= 3.4.2)
- libspatialite5 (>= 2.4.0)
- libsqlite3-0 (>= 3.5.9)
- libstdc++6 (>= 4.1.1)

Кажется проблема что у меня стояло для libgdal1h <= 1.9.0, а в репах сейчас максимум 1.11.2.
Поставил **1.11.3**. После пересборки на версии gdal - 2.1.0+39 надо проверить.

**Comment by simgislab** [comment]
да, отсюда http://qgis.org/debian, но пока что-то не помогает

**Comment by BishopGIS** [comment]
Вроде решилось, закрываем?
