### ISSUE TITLE
Ubuntu 16.04 LTS osm2pgsql cannot found libgeos.so

### ISSUE THREAD

**Issue by trolleway** [nextgis/ppa#3]
Чистая установка Ubuntu.
Если поставить

```
sudo apt-get install -y osm2pgsql
#Потом подключить наш репозиторий
sudo apt-add-repository -y ppa:nextgis/ppa
sudo apt-get update  -y
sudo apt-get install -y gdal-bin \
python-gdal \
python-psycopg2
```
То osm2pgsql запускается без ошибок.

Если ставить в обратном порядке
```
sudo apt-add-repository -y ppa:nextgis/ppa
sudo apt-get update  -y
sudo apt-get install -y gdal-bin \
python-gdal \
python-psycopg2

sudo apt-get install -y osm2pgsql
```
то osm2pgsql при запуске начнёт ругаться на отсутствие доступа к libgeos-чего-то-там.so (точный текст ошибки не помню, всё дома развёрнуто)

Если не воспроизведётся, то это наблюдалось на чистой убунте при выполнении этого скрипта. https://github.com/trolleway/osm-mostrans/blob/master/install.sh
Если osm2pgsql ставить в конце, то он не заработает.

**Comment by trolleway** [comment]
Ну точно! После подключения нашего ppa ломается libgeos
```
The following packages have been kept back:
  libgdal1i postgis postgresql-9.5-postgis-2.2
The following packages will be upgraded:
  libgeos-3.5.0 libgeos-c1v5 postgresql-9.5-postgis-scripts
```

```
~$ osm2pgsql
osm2pgsql: error while loading shared libraries: libgeos-3.5.0.so: cannot open s                                                            hared object file: No such file or directory

```

**Comment by BishopGIS** [comment]
Я понял в чем ошибка - починю

**Comment by BishopGIS** [comment]
Исправлено в 7985832c3fba6ac9b4f28e75d48bfe9cb5e7c7cb
