### ISSUE TITLE
cgal /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGAL_CoreExports.cmake not found

### ISSUE THREAD

**Issue by massich** [nextgis/ppa#5]
I'm trying to use your ppa to install cgal [here](https://github.com/openmeeg/openmeeg/pull/280) but it doesn't work because `CGAL_CoreExports.cmake` is not found.

see this section of `diff -u xxx/logs/toothless.log xxx/logs/travis_patchA.log` where `toothless` is the log of my laptop using `ubuntu 17.10` and `travis_patchA.log` is a travis container using `nextgis/ppa`.

```diff
 /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALConfig.cmake(79):  if(EXISTS /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGAL_CoreExports.cm
ake )
-/usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALConfig.cmake(81):  include(/usr/lib/x86_64-linux-gnu/cmake/CGAL/CGAL_CoreExports.cmake )
-/usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALConfig.cmake(83):  include(/usr/lib/x86_64-linux-gnu/cmake/CGAL/CGAL_CoreLibConfig.cmake )
 /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALConfig.cmake(86):  if(WITH_CGAL_Core )
```

Some more info regarding `libcgal-dev`: 

- In toothless:
```sh
❯ apt-cache policy libcgal-dev  
libcgal-dev:
  Installed: 4.9-1build2
  Candidate: 4.9-1build2
  Version table:
 *** 4.9-1build2 500
        500 http://archive.ubuntu.com/ubuntu artful/universe amd64 Packages
        100 /var/lib/dpkg/status

```

- In travis container: 
```sh
travis@8aa541f863ac:~/openmeeg/build$ apt-cache policy libcgal-dev
libcgal-dev:
  Installed: 4.9+17-0trusty1
  Candidate: 4.9+17-0trusty1
  Version table:
 *** 4.9+17-0trusty1 500
        500 http://ppa.launchpad.net/nextgis/ppa/ubuntu trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     4.2-5ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu trusty/universe amd64 Packages
```

**Comment by BishopGIS** [comment]
CGAL ppa/debian scripts are outdated and not supported any more. I removed CGAL from this repository and launchpad ppa. Please use CGAL from main ubuntu repositories: https://packages.ubuntu.com/search?keywords=libcgal-dev

Now in this repository supported only following libraries:

* GDAL
* GEOS
* OpenCAD
